name: "NTP Timeshow Scanner"
version: "1.0.2"
slug: "ntp_timeshow"
description: "Scan a subnet for NTP servers and publish offset statistics to MQTT"
url: "https://github.com/Kitsok/timeshow"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
options:
  network: "172.20.20.0/24"
  interval_seconds: 300
  timeout: 0.5
  workers: 64
  include_network_broadcast: false
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_topic: "timeshow/ntp_scan"
  mqtt_discovery: true
  mqtt_discovery_prefix: "homeassistant"
schema:
  network: str
  interval_seconds: int
  timeout: float
  workers: int
  include_network_broadcast: bool
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  mqtt_topic: str
  mqtt_discovery: bool
  mqtt_discovery_prefix: str
